CREATE TABLE usuario (
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         matricula VARCHAR(4) NOT NULL,
                         nome VARCHAR(50) NOT NULL,
                         email VARCHAR(50) NOT NULL,
                         senha VARCHAR(20) NOT NULL
);